# MARKDOWN FEATURES:
*NUMPY* OR  _NUMPY_ ----> Using single star OR underscore shows italic format of string
# NUMPY  ----> Use of single hash "#" in starting of word gives blue colour to string
** NUMPY ** ----> Use of double asterisk makes the word bold.

In [1]:
import numpy as np
print(np.__version__)

1.26.1


In [2]:
# 1D array ----> Called as Vector
import numpy as np
arr = np.array([1, 2, 3])         # arr = np.array((1, 2, 3)) 
print(type(arr),arr)
  

<class 'numpy.ndarray'> [1 2 3]


In [3]:
l=arr.tolist()
print(type(l),l)

<class 'list'> [1, 2, 3]


In [4]:
# 2D array ----> Called as Matrix
import numpy as np
arr = np.array([[1,2,3],           #arr = np.array(((1,2,3),(4,5,6,))) 
               [4,5,6]]) 
print(arr,type(arr))
print(np.arange(20))
print(arr[1][2])     # print(arr[1,2])
print(arr[0])

[[1 2 3]
 [4 5 6]] <class 'numpy.ndarray'>
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
6
[1 2 3]


In [46]:
b={"Ram":23,"Sham":24}
print(type(b))
a=np.array(b)
print(a)
print(type(a))
type(a)

<class 'dict'>
{'Ram': 23, 'Sham': 24}
<class 'numpy.ndarray'>


numpy.ndarray

In [6]:
# nD Array ----> Called as Tensor
# 3D array 
import numpy as np
c=np.array([[[1,2,3,4],[5,6,7,8]],
           [[9,10,11,12],[13,14,15,16]],
           [[17,18,19,20],[21,22,23,24]]])
print(c)
print(c[1,0,1])     # print(c[1][0][1])
print(c[1][0])

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]

 [[17 18 19 20]
  [21 22 23 24]]]
10
[ 9 10 11 12]


# Why it is useful:
Memory efficent container that provide fast numerical operations.
----> Here, array takes certainly less time to execute than list.

In [7]:
l=range(100)
%timeit [i**2 for i in l]

19.2 µs ± 2.48 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [8]:
import numpy as np;
arr=np.arange(100)
%timeit arr**2

1.33 µs ± 110 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


# BASIC FUNCTIONS OF ARRAY:

In [9]:
# 1.Finding dimension of array using ndim function
import numpy as np;
a=np.array([[4,8,2,9,1],
           [4,8,2,9,1]])
s=np.array([[[12]]])
k=np.array([[[12]]],ndmin=5)
print("Dimension:",a.ndim,"D")
print("Dimension:",s.ndim,"D")
print("Dimension:",k.ndim,"D")

Dimension: 2 D
Dimension: 3 D
Dimension: 5 D


In [10]:
# 2. shape function returns: A tuple whose elements give the lengths of the corresponding array dimensions. 
import numpy as np;
a=np.array([4,8,2,9,1])
b=np.array([[4,8,2,9],
           [4,8,2,9]])
c=np.array([[[4,8,2,9,1]],
            [[4,8,2,9,1]],
            [[4,8,2,9,1]]])
print(a.shape) 
print(b.shape) 
print(c.shape) 
print(len(a), len(b),len(c))

(5,)
(2, 4)
(3, 1, 5)
5 2 3


In [11]:
# 3. arange function having parameters as(start, end(exclusive),step)
import numpy as np
a=np.arange(1,10,2)
print(a)

[1 3 5 7 9]


In [12]:
# 4. np.linspace(start,stop,number of values) function returns number spaces evenly w.r.t interval.here,6 is the interval
import numpy as np
a=np.linspace(0,1,6)    # (1-0)/5
b=np.linspace(1,5,30)   # (5-1)/29
print(a)
print(b)

[0.  0.2 0.4 0.6 0.8 1. ]
[1.         1.13793103 1.27586207 1.4137931  1.55172414 1.68965517
 1.82758621 1.96551724 2.10344828 2.24137931 2.37931034 2.51724138
 2.65517241 2.79310345 2.93103448 3.06896552 3.20689655 3.34482759
 3.48275862 3.62068966 3.75862069 3.89655172 4.03448276 4.17241379
 4.31034483 4.44827586 4.5862069  4.72413793 4.86206897 5.        ]


In [13]:
# 5. np.ones() function will return an array of number 1 acc. to intervals written(We can give values in list or tuple)
import numpy as np;
a=np.ones([3,3])
b=np.ones((2,3),dtype=int)
print(b,"\n")
b=np.ones((2,3),dtype=float)    # 1. means 1.0
print(b,"\n")
c=np.ones((3,2))
print(a,"\n")
print(c)

[[1 1 1]
 [1 1 1]] 

[[1. 1. 1.]
 [1. 1. 1.]] 

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]] 

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [60]:
array3D = np.ones((2,2,5))
array3D

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

# MATHEMATICAL OPERATIONS

In [78]:
my2d_array = np.ones((3,6))
my2d_array
print(my2d_array + 3)

[[4. 4. 4. 4. 4. 4.]
 [4. 4. 4. 4. 4. 4.]
 [4. 4. 4. 4. 4. 4.]]


In [81]:
myarray=np.array([1,2,3,4,5])
np.cos(myarray)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219])

In [83]:
np.exp(myarray)

array([  2.71828183,   7.3890561 ,  20.08553692,  54.59815003,
       148.4131591 ])

In [82]:
np.log10(myarray)

array([0.        , 0.30103   , 0.47712125, 0.60205999, 0.69897   ])

In [84]:
myarray = np.zeros((4,4))
myarray[2,3] = 1
myarray

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [85]:
myarray > 0

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [False, False, False, False]])

In [86]:
nd_array = np.random.normal(10, 2, (3,4))
nd_array

array([[12.5194264 ,  8.84192759, 11.84209732, 12.46239355],
       [12.4001656 ,  9.6810768 , 10.41894363,  9.1549499 ],
       [ 7.03221348,  8.73454797,  8.56230832,  5.85191984]])

In [87]:
np.mean(nd_array)
# nd_array.mean()

9.79183086689923

In [88]:
np.std(nd_array)

2.1027782292770274

In [89]:
np.max(nd_array)

12.519426404655787

In [90]:
nd_array.max(axis=0)  # Gives max. value from each column

array([12.5194264 ,  9.6810768 , 11.84209732, 12.46239355])

In [91]:
nd_array.max(axis=1) # Gives max. value from each rows

array([12.5194264 , 12.4001656 ,  8.73454797])

In [49]:
# --------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# 6. np.zeros() function will return an array of number 0 acc. to intervals written(We can give values in list or tuple)
import numpy as np;
a=np.zeros([3,3])
b=np.zeros((2,3),dtype=int)
print(b,"\n")
b=np.zeros((2,3),dtype=float)    # 0. means 0.0
print(b,"\n")
c=np.zeros((3,2))
print(a,"\n")
print(c)

[[0 0 0]
 [0 0 0]] 

[[0. 0. 0.]
 [0. 0. 0.]] 

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] 

[[0. 0.]
 [0. 0.]
 [0. 0.]]


# COPYING THE SHAPE:
We can do this using "like" function..

In [53]:
a=np.ones([3,3])
same_shape_array=np.zeros_like(a)
same_shape_array


array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [56]:
b=np.zeros([3,3])
same_shape_array=np.ones_like(b)
same_shape_array

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [15]:
# 7. np.eye() function returns 2D array have one on diagonal and zero elsewhere
import numpy as np;
a=np.eye(4)              # np.identity(4) also works same
b=np.eye(3)
c=np.eye(3,2)  # 3 is no. of rows and 2 is no. of columns
print(a,"\n")
print(b,"\n")
print(c)          # it is not identity matrix

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]] 

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 

[[1. 0.]
 [0. 1.]
 [0. 0.]]


In [16]:
# 8. Create array using diag function
import numpy as np;
a=np.diag([1,2,3,4]) # construct a diagonal array
c=np.diag([1.,2,3,4]) # construct a diagonal array
print(a,"\n")
print(c,"\n")
b=np.diag(a) # extract diagonal
print(b)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]] 

[[1. 0. 0. 0.]
 [0. 2. 0. 0.]
 [0. 0. 3. 0.]
 [0. 0. 0. 4.]] 

[1 2 3 4]


In [17]:
# Flattening Arrays --> Converting multidimensional array to 1D array
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
a.reshape(-1)


array([1, 2, 3, 4, 5, 6])

In [18]:
# 9. Create array using random module where rand & randn are one of the function of random module
import numpy as np;
a=np.random.rand(5)
b=np.random.randn(5)  # it can include negative numbers also
c=np.random.randint(0,20,15)  # start,end,length
print(a)      # our output can be shown as: array([0.03880731 0.73273688 0.11557813 0.38140661 0.13596918])
print(b)
print(c)

[0.95392893 0.92980347 0.80120162 0.86706818 0.13321758]
[-0.45947763  0.89622133 -0.40092647 -0.09347057 -0.06677732]
[17 11  7  8  1 12 18  7 13  6 10  9 19  4 10]


In [58]:
normal_array = np.random.normal(loc=10, scale=2, size=(3,4))   # loc : mean value, scale : standard deviation
normal_array

array([[12.1481574 ,  9.854434  , 11.41250434,  9.77005279],
       [11.2837753 , 11.41609433,  9.14189779,  7.52975502],
       [ 7.89939151, 10.18141703, 13.18421224,  6.51776785]])

In [57]:
# lam (short for "lambda") represents the rate parameter of the Poisson distribution.
# It means that on average, 5 events are expected to occur in each interval withh somme variability.
np.random.poisson(lam=5, size=(3,4))

array([[5, 3, 4, 5],
       [5, 4, 7, 3],
       [2, 4, 5, 9]])

# IMPORTING ARRAYS
*Loading and saving arrays*

In [67]:
array1 = np.random.normal(10, 2, (4,5))
array1


array([[11.13422567,  9.2270869 , 15.13291535, 13.89005163,  9.47420977],
       [13.05750629,  7.81823934, 13.88405639,  7.80739642,  8.54557965],
       [ 9.90801157, 10.94020434,  7.61942455, 11.25366869, 12.33113373],
       [ 8.82309894, 10.03026749, 10.10238203, 11.42899308, 11.20047212]])

In [68]:
np.save('my_saved_array.npy', array1)

In [69]:
ls   # To check that if the file is saved or not

 Volume in drive C has no label.
 Volume Serial Number is 369A-7D37

 Directory of c:\Users\hp\Desktop\Python


 Directory of c:\Users\hp\Desktop\Python


 Directory of c:\Users\hp\Desktop\Python


 Directory of c:\Users\hp\Desktop\Python


 Directory of c:\Users\hp\Desktop\Python


 Directory of c:\Users\hp\Desktop\Python


 Directory of c:\Users\hp\Desktop\Python


 Directory of c:\Users\hp\Desktop\Python


 Directory of c:\Users\hp\Desktop\Python


 Directory of c:\Users\hp\Desktop\Python


 Directory of c:\Users\hp\Desktop\Python



File Not Found


In [70]:
new_array = np.load('my_saved_array.npy')
new_array

array([[11.13422567,  9.2270869 , 15.13291535, 13.89005163,  9.47420977],
       [13.05750629,  7.81823934, 13.88405639,  7.80739642,  8.54557965],
       [ 9.90801157, 10.94020434,  7.61942455, 11.25366869, 12.33113373],
       [ 8.82309894, 10.03026749, 10.10238203, 11.42899308, 11.20047212]])

In [66]:
# If you have several arrays that belong together, you can also save them in a single file using np.savez in npz format.
# Let's create a second array:
array2 = np.random.normal(10, 2, (1,2))
array2

array([[ 7.67655285, 12.85537569]])

In [71]:
np.savez('multiple_arrays.npz', array_to_save=array1, array_to_save2=array2)

In [72]:
load_multiple = np.load('multiple_arrays.npz')
type(load_multiple)

numpy.lib.npyio.NpzFile

In [74]:
load_multiple.files

['array_to_save', 'array_to_save2']

In [75]:
load_multiple.get('array_to_save2')

array([[ 7.67655285, 12.85537569]])

#  _BASIC DATA TYPES_

In [47]:
# Finding data types
import numpy as np;
a=np.arange(100)
print(a.dtype)
a.dtype

int32


dtype('int32')

In [20]:
# complex datatypes
import numpy as np;
a=np.array([1+2j,2+4j])
print(a.dtype)
# boolean datatype
b=np.array([True,False,True,True])
print(b.dtype)
# String datatype
c=np.array(['Rahul','Uma','John'])  # here,U means Unicode datatype
print(c.dtype)

complex128
bool
<U5


# _Datatype_
'b' - boolean
'i' - (signed) integer
'u' - unsigned integer
'f' - floating-point
'c' - complex-floating point
'm' - timedelta
'M' - datetime
'O' (Python) - objects 
'S', 'a' (byte-) - string 
'U' - Unicode
'V' - raw data

# _INDEXING_

In [21]:
# Finding index and changing value of particular index in 1 D Array
import numpy as np;
a=np.arange(10)
print(a)
print(a[3])
a[5]=9
print(a)

[0 1 2 3 4 5 6 7 8 9]
3
[0 1 2 3 4 9 6 7 8 9]


In [22]:
# Finding index and changing value of particular index in 1 D Array
arr=np.arange(12)
arr1=arr.reshape(3,4)
print("Array arr1:\n",arr1)
print("Element at 0th row and 0th column of arr1 is:",arr1[0,0])
print("Element at 1st row and 2nd column  of arr1 is:",arr1[1,2])
arr1[1,2]=8                                                        # Changing value 
print("Element at 1st row and 2nd column  of arr1 is:",arr1[1,2])

Array arr1:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Element at 0th row and 0th column of arr1 is: 0
Element at 1st row and 2nd column  of arr1 is: 6
Element at 1st row and 2nd column  of arr1 is: 8


In [23]:
# Picking a row and a column in 2D Numpy Array
import numpy as np
arr=np.arange(12)
arr1=arr.reshape(3,4)
print("Array arr1:\n",arr1)
print("\n")
print("1st index row :\n",arr1[1])
print("\n")
print("2nd index column :\n",arr1[:,2])

Array arr1:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


1st index row :
 [4 5 6 7]


2nd index column :
 [ 2  6 10]


In [92]:
a=np.array([2,8,3,1,0,10])
np.sort(a)

array([ 0,  1,  2,  3,  8, 10])

In [24]:
#  Indexing in 3D ARRAY
import numpy as np
arr=np.arange(12)
arr1=arr.reshape(2,2,3)
print("Array arr1:\n",arr1)   
print("Element:",arr1[1,0,2]) # here,[1,0,2]=[i,j,k] where i,j,k stands for 1D,2D,3D

Array arr1:
 [[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
Element: 8


In [25]:
# Picking a row or a column in 3D Array
import numpy as np
arr=np.arange(12)
arr1=arr.reshape(2,2,3)
print("Array arr1:\n",arr1)
print("1st row :",arr1[0,1])
print("0 and 2nd column of 1st index row :",arr1[1,:,[0,2]])
# Subarrays are dependent on normal arrays i.e. any changes made in normal array will reflect changes in sub arrays
print("2nd column of 1st index row :",arr1[1,:,[2]])

Array arr1:
 [[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
1st row : [3 4 5]
0 and 2nd column of 1st index row : [[ 6  9]
 [ 8 11]]
2nd column of 1st index row : [[ 8 11]]


In [26]:
# Picking a matrix in 3D ARRAY
import numpy as np
arr=np.arange(12)
arr1=arr.reshape(2,2,3)
print("Array arr1:\n",arr1)
print("\n")
print("1st matrix :\n",arr1[1])

Array arr1:
 [[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


1st matrix :
 [[ 6  7  8]
 [ 9 10 11]]


In [27]:
# Indexing with an array of integers
a=np.arange(0,100,10)
print(a)
# Indexing can be done with array of integers where same index can be repeated
print(a[[2,3,2,4,2]])
a[[7,9]]=(-290,89)
print(a)
a[[7,9]]=-290
print(a)

[ 0 10 20 30 40 50 60 70 80 90]
[20 30 20 40 20]
[   0   10   20   30   40   50   60 -290   80   89]
[   0   10   20   30   40   50   60 -290   80 -290]


In [28]:
import numpy as np
arr = np.arange(12)
print(arr)
print("Element at index 6 of an array arr:",arr[6])
print("Element from index 3 to 8 of an array arr:",arr[3:8])

[ 0  1  2  3  4  5  6  7  8  9 10 11]
Element at index 6 of an array arr: 6
Element from index 3 to 8 of an array arr: [3 4 5 6 7]


In [29]:
import numpy as np 
arr = np.array([[[1,2,3],[3,4,5]],[[5,6,7],[9,10,11]]]) 
print ("The array is:") 
print (arr )
print ('\n')
## Access the last dimension
print("using simple indexing:\n",arr[:,:,0])
print("using ellipsis:\n ",arr[...,0])

The array is:
[[[ 1  2  3]
  [ 3  4  5]]

 [[ 5  6  7]
  [ 9 10 11]]]


using simple indexing:
 [[1 3]
 [5 9]]
using ellipsis:
  [[1 3]
 [5 9]]


In [30]:
# Advance indexing
import numpy as np
arr = np.array([[11 ,12 ],[13 ,14 ],[15 ,16 ]])
print(arr)
print(arr[[0 ,1 ,2 ],[0 ,0 ,1]])   # coordinates (0,0)----> 11, (1,0)---->13, and (2,1)---->16

[[11 12]
 [13 14]
 [15 16]]
[11 13 16]


In [31]:
# Using purely integer indexing
import numpy as np
arr=np.arange(1,10,2)
print("Elements of array: ",arr)
arr1=arr[np.array([4,0,2,-1,-2])]
print("Indexed Elements of array arr: ",arr1)

Elements of array:  [1 3 5 7 9]
Indexed Elements of array arr:  [9 1 5 9 7]


In [32]:
# Using boolean indexing
import numpy as np
arr = np.array([11,6,41,10,29,50,55,45])
print(arr[arr>35])

[41 50 55 45]


In [33]:
# For multidimensional array,indexes are tuple of integers                    0  1  2 (indexing)
a=np.diag([1,2,3])                                                   #   0->  1  0  0
print(a[2,2])                                                        #   1->  0  2  0
# Access element of 2 indexing of row and 2 indexing of column       #   2->  0  0  3
b=np.diag([3,4])
print(b[1,0]) 

3
0


In [34]:
a=np.diag([1,2,3])  
a[2,1]=5
print(a)

[[1 0 0]
 [0 2 0]
 [0 5 3]]


# _SLICING_

In [35]:
# Slicing 1D Numpy Array
import numpy as np
arr = np.arange(6)
print("array arr:",arr)
print("sliced element of array:",arr[1:5])

array arr: [0 1 2 3 4 5]
sliced element of array: [1 2 3 4]


In [36]:
# Slicing 2D Numpy Array
import numpy as np
arr=np.arange(12)
arr1=arr.reshape(3,4)
print("Array arr1:\n",arr1)
print("\n")
print("elements of 1st row and 1st column upto last column :\n",arr1[1:,1:4])

Array arr1:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


elements of 1st row and 1st column upto last column :
 [[ 5  6  7]
 [ 9 10 11]]


In [37]:
# Slicing 3D Array
import numpy as np

arr = np.array([[[1, 2, 3], [11, 13, 14], [21, 22, 23]],
               [[4, 5, 6], [15, 16, 17], [24, 25, 26]],
               [[7, 8, 9], [18, 19, 20], [27, 28, 29]]])
print(arr)
print("\n")
print("sliced array: \n",arr[:2,1:,:2])  

[[[ 1  2  3]
  [11 13 14]
  [21 22 23]]

 [[ 4  5  6]
  [15 16 17]
  [24 25 26]]

 [[ 7  8  9]
  [18 19 20]
  [27 28 29]]]


sliced array: 
 [[[11 13]
  [21 22]]

 [[15 16]
  [24 25]]]


In [38]:
# Full slicing of 2D Array
import numpy as np
arr = np.arange(12)
arr1=arr.reshape(3,4)
print(arr1)
print("\n")
print("2-D array sliced from first row to last:\n",arr1[1:3])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


2-D array sliced from first row to last:
 [[ 4  5  6  7]
 [ 8  9 10 11]]


In [39]:
# Full slicing of 3D Array
import numpy as np
arr = np.array([[[1, 2, 3], [11, 13, 14], [21, 22, 23]],
               [[4, 5, 6], [15, 16,17], [24, 25, 26]],
               [[7, 8, 9], [18, 19, 20], [27, 28, 29]]])
print("3-D array:\n",arr)   
print("\n")
print("3-D array sliced from first row to last:\n",arr[1:,:,:])

3-D array:
 [[[ 1  2  3]
  [11 13 14]
  [21 22 23]]

 [[ 4  5  6]
  [15 16 17]
  [24 25 26]]

 [[ 7  8  9]
  [18 19 20]
  [27 28 29]]]


3-D array sliced from first row to last:
 [[[ 4  5  6]
  [15 16 17]
  [24 25 26]]

 [[ 7  8  9]
  [18 19 20]
  [27 28 29]]]


In [40]:
# Negative slicing and indexing
import numpy as np
arr = np.array([10,20,30,40,50,60,70,80,90])
print("Element at index 2 or -7 of an array arr:",arr[-7])
print("Sliced Element from index -8 or 2 and -3 or 6 of an array arr:",arr[-8:-3])

Element at index 2 or -7 of an array arr: 30
Sliced Element from index -8 or 2 and -3 or 6 of an array arr: [20 30 40 50 60]


In [93]:
# REVERSING ARRAY
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
np.flip(arr)

array([8, 7, 6, 5, 4, 3, 2, 1])

# In which method can we assign a single assignment or iterable? 
ANS. In indexing only
# In how many ways can we perform indexing in NumPy? 
ANS. 2 (Basic indexing and advance indexing)

In [41]:
a=np.arange(10)
print(a[1:8:2])

[1 3 5 7]


In [42]:
# We can also combine assignment and slicing
a=np.arange(10)
a[5:]=20
print(a)
b=np.arange(5)
a[5:]=b[::-1]
print(a)

[ 0  1  2  3  4 20 20 20 20 20]
[0 1 2 3 4 4 3 2 1 0]


# _COPIES AND VIEWS

In [43]:
a=np.arange(10)
print(a)
b=a[::2]
print(b)
c=a[::2].copy()
print(c)
print(np.shares_memory(a,b))
print(np.shares_memory(a,c))

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]
[0 2 4 6 8]
True
False


# _FANCY INDEXING_ : Numpy arrays can be indexed with slices but also with boolean or integer arrays(mask).This method is called fancy indexing.
It creates copies not views.

In [44]:
# Using Boolean mask
a=np.random.randint(0,20,15)
print(a)
mask=(a%2==0)      #  Here,a%2==0 is boolean condition
b=a[mask]
print(b)
a[mask]=-1
print(a)

[13 19  3  6  6  1 18  1 10  5 12  9 13  9 12]
[ 6  6 18 10 12 12]
[13 19  3 -1 -1  1 -1  1 -1  5 -1  9 13  9 -1]


# _NUMPY ARRAY ITERATIONS Using for and while loops_
Nditer is a multidimensional iterator object in the NumPy package that can traverse an array efficiently.
We can modify the array value by using an optional parameter of the nditer object called Op flags (operand flags).
We have to perform multiple loops to iterate over a multidimensional array. To avoid using multiple loops, we use a NumPy function called nditer.

In [45]:
# Using for loops:
import numpy as np
arr = np.arange(12)
arr1=arr.reshape(3,4)
print("arr1:\n",arr1)
print("Traversed array:")
for i in arr1:
   for j in i:
    print(j, end=' ')
# Using nditer function:
"""for i in np.nditer(arr1):
   print(i, end=' ')"""

arr1:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Traversed array:
0 1 2 3 4 5 6 7 8 9 10 11 

"for i in np.nditer(arr1):\n   print(i, end=' ')"

In [94]:
x = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
x.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

# QUESTIONS :

In [30]:
# Replace all odd numbers in the given array with -1
import numpy as np
exercise_1 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
for i in exercise_1:
    if i%2!=0:
        exercise_1[i]=-1
print(exercise_1)


[ 0 -1  2 -1  4 -1  6 -1  8 -1]
[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [35]:
# Replace all odd numbers in the given array with -1 without changing original array 
arr_1 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
out = np.where(arr_1 % 2 != 0, -1, arr_1)
print(out)
print(arr_1)


[ 0 -1  2 -1  4 -1  6 -1  8 -1]
[0 1 2 3 4 5 6 7 8 9]


In [20]:
# Convert a 1-D array into a 2-D array with 3 rows
exercise_2 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8])
arr=exercise_2.reshape(3,3)
# arr=exercise_2.reshape(3, -1)  # Setting to -1 automatically decides the number of cols
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [21]:
# Add 202 to all the values in given array
exercise_3 = np.arange(4).reshape(2,-1)
print(exercise_3+202)

[[202 203]
 [204 205]]


In [25]:
# Generate a 1-D array of 10 random integers. Each integer should be a number between 30 and 40 (inclusive)
lst=[]
for i in range(10):
    digit=np.random.randint(30,41)
    lst.append(digit)
arr=np.array(lst)
print(arr)

[36 37 31 39 33 34 39 30 30 32]


In [26]:
# Find the positions of:
# (i) elements in x where its value is more than its corresponding element in y 
x = np.array([21, 64, 86, 22, 74, 55, 81, 79, 90, 89]) 
y = np.array([21, 7, 3, 45, 10, 29, 55, 4, 37, 18])
lst=[]
for i in range(len(x)):
    if x[i] > y[i]:
        lst.append(i)
arr=np.array(lst)
print(arr)

[1 2 4 5 6 7 8 9]


In [27]:
# (ii) elements in x where its value is equals to its corresponding element in y.
x = np.array([21, 64, 86, 22, 74, 55, 81, 79, 90, 89]) 
y = np.array([21, 7, 3, 45, 10, 29, 55, 4, 37, 18])
lst=[]
for i in range(len(x)):
    if x[i] == y[i]:
        lst.append(i)
arr=np.array(lst)
print(arr)

[0]


In [29]:
# Extract the first four columns of this 2-D array
exercise_6 = np.arange(100).reshape(5,-1)
arr=exercise_6[:,0:4]
print(arr)

[[ 0  1  2  3]
 [20 21 22 23]
 [40 41 42 43]
 [60 61 62 63]
 [80 81 82 83]]


In [48]:
# Stacking two arrays vertically
a = np.arange(10).reshape(2,-1)
b = np.repeat(2, 10).reshape(2,-1)
print("b:","\n",b,"\n")
arr=np.concatenate([a,b])
# np.concatenate([a,b],axis=0)
print(arr)

b: 
 [[2 2 2 2 2]
 [2 2 2 2 2]] 

[[0 1 2 3 4]
 [5 6 7 8 9]
 [2 2 2 2 2]
 [2 2 2 2 2]]


In [49]:
# Stacking two arrays horizontally
a = np.arange(10).reshape(2,-1)
b = np.repeat(2, 10).reshape(2,-1)
arr=np.concatenate([a,b],axis=1)
print(arr)

[[0 1 2 3 4 2 2 2 2 2]
 [5 6 7 8 9 2 2 2 2 2]]


In [92]:
#  Create the following pattern without hardcoding. Use only numpy functions and the below input array a.
a = np.array([1,2,3])
lst=np.repeat(a,3)
arr=np.concatenate([lst,a])
print(arr)

[1 1 1 2 2 2 3 3 3 1 2 3]


In [96]:
# How to get the common items between two python numpy arrays?
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
lst=[]
for i in range(len(a)):
    if a[i] == b[i]:
        lst.append(a[i])
arr=np.array(lst)
arr_1=np.unique(arr)
print(arr_1)


[2 4]


In [106]:
# How to remove from one array those items that exist in another?
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
for i in range(len(a)):
    for j in range(len(b)):
        if a[i]==b[j]:
            arr=np.delete(a,i)   # np.delete(array from which item need to be deleted, index of an item to be deleted)
print(arr)

[1 2 3 4]


In [107]:
# Get all items between 5 and 10 from a.
a = np.array([2, 6, 1, 9, 10, 3, 27])
lst=[]
for i in a:
    if i>5 and i<10:
        lst.append(i)
arr=np.array(lst)
print(arr)

[6 9]
