# MARKDOWN FEATURES:
*NUMPY* OR  _NUMPY_ ----> Using single star OR underscore shows italic format of string
# NUMPY  ----> Use of single hash "#" in starting of word gives blue colour to string
** NUMPY ** ----> Use of double asterisk makes the word bold.

In [1]:
import numpy as np
print(np.__version__)

1.26.1


In [1]:
# 1D array ----> Called as Vector
import numpy as np
arr = np.array([1, 2, 3])         # arr = np.array((1, 2, 3)) 
print(arr)
  

[1 2 3]


In [1]:
# 2D array ----> Called as Matrix
import numpy as np
arr = np.array([[1,2,3],           #arr = np.array(((1,2,3),(4,5,6,))) 
               [4,5,6]]) 
print(arr,type(arr))
print(np.arange(20))
print(arr[1][2])     # print(arr[1,2])
print(arr[0])

[[1 2 3]
 [4 5 6]] <class 'numpy.ndarray'>
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
6
[1 2 3]


In [4]:
b={"Ram":23,"Sham":24}
print(type(b))
a=np.array(b)
print(a)
print(type(a))

<class 'dict'>
{'Ram': 23, 'Sham': 24}
<class 'numpy.ndarray'>


In [9]:
# nD Array ----> Called as Tensor
# 3D array 
import numpy as np
c=np.array([[[1,2,3,4],[5,6,7,8]],
           [[9,10,11,12],[13,14,15,16]],
           [[17,18,19,20],[21,22,23,24]]])
print(c)
print(c[1,0,1])     # print(c[1][0][1])
print(c[1][0])

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]

 [[17 18 19 20]
  [21 22 23 24]]]
10
[ 9 10 11 12]


# Why it is useful:
Memory efficent container that provide fast numerical operations.
----> Here, array takes certainly less time to execute than list.

In [11]:
l=range(100)
%timeit [i**2 for i in l]

7.02 µs ± 206 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [12]:
import numpy as np;
arr=np.arange(100)
%timeit arr**2

718 ns ± 20.8 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


# BASIC FUNCTIONS OF ARRAY:

In [3]:
# 1.Finding dimension of array using ndim function
import numpy as np;
a=np.array([[4,8,2,9,1],
           [4,8,2,9,1]])
s=np.array([[[12]]])
k=np.array([[[12]]],ndmin=5)
print("Dimension:",a.ndim,"D")
print("Dimension:",s.ndim,"D")
print("Dimension:",k.ndim,"D")

Dimension: 2 D
Dimension: 3 D
Dimension: 5 D


In [25]:
# 2. shape function returns: A tuple whose elements give the lengths of the corresponding array dimensions. 
import numpy as np;
a=np.array([4,8,2,9,1])
b=np.array([[4,8,2,9],
           [4,8,2,9]])
c=np.array([[[4,8,2,9,1]],
            [[4,8,2,9,1]],
            [[4,8,2,9,1]]])
print(a.shape) 
print(b.shape) 
print(c.shape) 
print(len(a), len(b),len(c))

(5,)
(2, 4)
(3, 1, 5)
5 2 3


In [28]:
# 3. arange function having parameters as(start, end(exclusive),step)
import numpy as np
a=np.arange(1,10,2)
print(a)

[1 3 5 7 9]


In [30]:
# 4. np.linspace(start,stop,number of values) function returns number spaces evenly w.r.t interval.here,6 is the interval
import numpy as np
a=np.linspace(0,1,6)    # (1-0)/5
b=np.linspace(1,5,30)   # (5-1)/29
print(a)
print(b)

[0.  0.2 0.4 0.6 0.8 1. ]
[1.         1.13793103 1.27586207 1.4137931  1.55172414 1.68965517
 1.82758621 1.96551724 2.10344828 2.24137931 2.37931034 2.51724138
 2.65517241 2.79310345 2.93103448 3.06896552 3.20689655 3.34482759
 3.48275862 3.62068966 3.75862069 3.89655172 4.03448276 4.17241379
 4.31034483 4.44827586 4.5862069  4.72413793 4.86206897 5.        ]


In [41]:
# 5. np.ones() function will return an array of number 1 acc. to intervals written(We can give values in list or tuple)
import numpy as np;
a=np.ones([3,3])
b=np.ones((2,3),dtype=int)
print(b,"\n")
b=np.ones((2,3),dtype=float)    # 1. means 1.0
print(b,"\n")
c=np.ones((3,2))
print(a,"\n")
print(c)

[[1 1 1]
 [1 1 1]] 

[[1. 1. 1.]
 [1. 1. 1.]] 

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]] 

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [42]:
# 6. np.zeros() function will return an array of number 0 acc. to intervals written(We can give values in list or tuple)
import numpy as np;
a=np.zeros([3,3])
b=np.zeros((2,3),dtype=int)
print(b,"\n")
b=np.zeros((2,3),dtype=float)    # 0. means 0.0
print(b,"\n")
c=np.zeros((3,2))
print(a,"\n")
print(c)

[[0 0 0]
 [0 0 0]] 

[[0. 0. 0.]
 [0. 0. 0.]] 

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] 

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [2]:
# 7. np.eye() function returns 2D array have one on diagonal and zero elsewhere
import numpy as np;
a=np.eye(4)              # np.identity(4) also works same
b=np.eye(3)
c=np.eye(3,2)  # 3 is no. of rows and 2 is no. of columns
print(a,"\n")
print(b,"\n")
print(c)          # it is not identity matrix

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]] 

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 

[[1. 0.]
 [0. 1.]
 [0. 0.]]


In [4]:
# 8. Create array using diag function
import numpy as np;
a=np.diag([1,2,3,4]) # construct a diagonal array
c=np.diag([1.,2,3,4]) # construct a diagonal array
print(a,"\n")
print(c,"\n")
b=np.diag(a) # extract diagonal
print(b)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]] 

[[1. 0. 0. 0.]
 [0. 2. 0. 0.]
 [0. 0. 3. 0.]
 [0. 0. 0. 4.]] 

[1 2 3 4]


In [6]:
# 9. Create array using random module where rand & randn are one of the function of random module
import numpy as np;
a=np.random.rand(5)
b=np.random.randn(5)  # it can include negative numbers also
c=np.random.randint(0,20,15)  # start,end,length
print(a)      # our output can be shown as: array([0.03880731 0.73273688 0.11557813 0.38140661 0.13596918])
print(b)
print(c)

[0.03725295 0.10054731 0.42988567 0.38561168 0.17037946]
[-0.32278727 -0.15715623  0.2005538  -1.31534813 -1.66400346]
[13 17  7 18  0  2  6 14 12 15 15  3 19 12 19]


#  _BASIC DATA TYPES_

In [56]:
# Finding data types
import numpy as np;
a=np.arange(100)
print(a.dtype)

int32


In [60]:
# complex datatypes
import numpy as np;
a=np.array([1+2j,2+4j])
print(a.dtype)
# boolean datatype
b=np.array([True,False,True,True])
print(b.dtype)
# String datatype
c=np.array(['Rahul','Uma','John'])  # here,U means Unicode datatype
print(c.dtype)

complex128
bool
<U5


# _Datatype_
'b' - boolean
'i' - (signed) integer
'u' - unsigned integer
'f' - floating-point
'c' - complex-floating point
'm' - timedelta
'M' - datetime
'O' (Python) - objects 
'S', 'a' (byte-) - string 
'U' - Unicode
'V' - raw data

# _INDEXING_

In [8]:
# Finding index and changing value of particular index in 1 D Array
import numpy as np;
a=np.arange(10)
print(a)
print(a[3])
a[5]=9
print(a)

[0 1 2 3 4 5 6 7 8 9]
3
[0 1 2 3 4 9 6 7 8 9]


In [8]:
# Finding index and changing value of particular index in 1 D Array
arr=np.arange(12)
arr1=arr.reshape(3,4)
print("Array arr1:\n",arr1)
print("Element at 0th row and 0th column of arr1 is:",arr1[0,0])
print("Element at 1st row and 2nd column  of arr1 is:",arr1[1,2])
arr1[1,2]=8                                                        # Changing value 
print("Element at 1st row and 2nd column  of arr1 is:",arr1[1,2])

Array arr1:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Element at 0th row and 0th column of arr1 is: 0
Element at 1st row and 2nd column  of arr1 is: 6
Element at 1st row and 2nd column  of arr1 is: 8


In [19]:
# Picking a row and a column in 2D Numpy Array
import numpy as np
arr=np.arange(12)
arr1=arr.reshape(3,4)
print("Array arr1:\n",arr1)
print("\n")
print("1st index row :\n",arr1[1])
print("\n")
print("2nd index column :\n",arr1[:,2])

Array arr1:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


1st index row :
 [4 5 6 7]


2nd index column :
 [ 2  6 10]


In [20]:
#  Indexing in 3D ARRAY
import numpy as np
arr=np.arange(12)
arr1=arr.reshape(2,2,3)
print("Array arr1:\n",arr1)   
print("Element:",arr1[1,0,2]) # here,[1,0,2]=[i,j,k] where i,j,k stands for 1D,2D,3D

Array arr1:
 [[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
Element: 8


In [37]:
# Picking a row or a column in 3D Array
import numpy as np
arr=np.arange(12)
arr1=arr.reshape(2,2,3)
print("Array arr1:\n",arr1)
print("1st row :",arr1[0,1])
print("0 and 2nd column of 1st index row :",arr1[1,:,[0,2]])
print("2nd column of 1st index row :",arr1[1,:,[2]])

Array arr1:
 [[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
1st row : [3 4 5]
0 and 2nd column of 1st index row : [[ 6  9]
 [ 8 11]]
2nd column of 1st index row : [[ 8 11]]


In [39]:
# Picking a matrix in 3D ARRAY
import numpy as np
arr=np.arange(12)
arr1=arr.reshape(2,2,3)
print("Array arr1:\n",arr1)
print("\n")
print("1st matrix :\n",arr1[1])

Array arr1:
 [[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


1st matrix :
 [[ 6  7  8]
 [ 9 10 11]]


In [10]:
# Indexing with an array of integers
a=np.arange(0,100,10)
print(a)
# Indexing can be done with array of integers where same index can be repeated
print(a[[2,3,2,4,2]])
a[[7,9]]=(-290,89)
print(a)
a[[7,9]]=-290
print(a)

[ 0 10 20 30 40 50 60 70 80 90]
[20 30 20 40 20]
[   0   10   20   30   40   50   60 -290   80   89]
[   0   10   20   30   40   50   60 -290   80 -290]


In [40]:
import numpy as np
arr = np.arange(12)
print(arr)
print("Element at index 6 of an array arr:",arr[6])
print("Element from index 3 to 8 of an array arr:",arr[3:8])

[ 0  1  2  3  4  5  6  7  8  9 10 11]
Element at index 6 of an array arr: 6
Element from index 3 to 8 of an array arr: [3 4 5 6 7]


In [41]:
import numpy as np 
arr = np.array([[[1,2,3],[3,4,5]],[[5,6,7],[9,10,11]]]) 
print ("The array is:") 
print (arr )
print ('\n')
## Access the last dimension
print("using simple indexing:\n",arr[:,:,0])
print("using ellipsis:\n ",arr[...,0])

The array is:
[[[ 1  2  3]
  [ 3  4  5]]

 [[ 5  6  7]
  [ 9 10 11]]]


using simple indexing:
 [[1 3]
 [5 9]]
using ellipsis:
  [[1 3]
 [5 9]]


In [13]:
# Advance indexing
import numpy as np
arr = np.array([[11 ,12 ],[13 ,14 ],[15 ,16 ]])
print(arr)
print(arr[[0 ,1 ,2 ],[0 ,0 ,1]])   # coordinates (0,0)----> 11, (1,0)---->13, and (2,1)---->16

[[11 12]
 [13 14]
 [15 16]]
[11 13 16]


In [44]:
# Using purely integer indexing
import numpy as np
arr=np.arange(1,10,2)
print("Elements of array: ",arr)
arr1=arr[np.array([4,0,2,-1,-2])]
print("Indexed Elements of array arr: ",arr1)

Elements of array:  [1 3 5 7 9]
Indexed Elements of array arr:  [9 1 5 9 7]


In [45]:
# Using boolean indexing
import numpy as np
arr = np.array([11,6,41,10,29,50,55,45])
print(arr[arr>35])

[41 50 55 45]


In [66]:
# For multidimensional array,indexes are tuple of integers                    0  1  2 (indexing)
a=np.diag([1,2,3])                                                   #   0->  1  0  0
print(a[2,2])                                                        #   1->  0  2  0
# Access element of 2 indexing of row and 2 indexing of column       #   2->  0  0  3
b=np.diag([3,4])
print(b[1,0]) 

3
0


In [64]:
a=np.diag([1,2,3])  
a[2,1]=5
print(a)

[[1 0 0]
 [0 2 0]
 [0 5 3]]


# _SLICING_

In [46]:
# Slicing 1D Numpy Array
import numpy as np
arr = np.arange(6)
print("array arr:",arr)
print("sliced element of array:",arr[1:5])

array arr: [0 1 2 3 4 5]
sliced element of array: [1 2 3 4]


In [47]:
# Slicing 2D Numpy Array
import numpy as np
arr=np.arange(12)
arr1=arr.reshape(3,4)
print("Array arr1:\n",arr1)
print("\n")
print("elements of 1st row and 1st column upto last column :\n",arr1[1:,1:4])

Array arr1:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


elements of 1st row and 1st column upto last column :
 [[ 5  6  7]
 [ 9 10 11]]


In [48]:
# Slicing 3D Array
import numpy as np

arr = np.array([[[1, 2, 3], [11, 13, 14], [21, 22, 23]],
               [[4, 5, 6], [15, 16, 17], [24, 25, 26]],
               [[7, 8, 9], [18, 19, 20], [27, 28, 29]]])
print(arr)
print("\n")
print("sliced array: \n",arr[:2,1:,:2])  

[[[ 1  2  3]
  [11 13 14]
  [21 22 23]]

 [[ 4  5  6]
  [15 16 17]
  [24 25 26]]

 [[ 7  8  9]
  [18 19 20]
  [27 28 29]]]


sliced array: 
 [[[11 13]
  [21 22]]

 [[15 16]
  [24 25]]]


In [50]:
# Full slicing of 2D Array
import numpy as np
arr = np.arange(12)
arr1=arr.reshape(3,4)
print(arr1)
print("\n")
print("2-D array sliced from first row to last:\n",arr1[1:3])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


2-D array sliced from first row to last:
 [[ 4  5  6  7]
 [ 8  9 10 11]]


In [51]:
# Full slicing of 3D Array
import numpy as np
arr = np.array([[[1, 2, 3], [11, 13, 14], [21, 22, 23]],
               [[4, 5, 6], [15, 16,17], [24, 25, 26]],
               [[7, 8, 9], [18, 19, 20], [27, 28, 29]]])
print("3-D array:\n",arr)   
print("\n")
print("3-D array sliced from first row to last:\n",arr[1:,:,:])

3-D array:
 [[[ 1  2  3]
  [11 13 14]
  [21 22 23]]

 [[ 4  5  6]
  [15 16 17]
  [24 25 26]]

 [[ 7  8  9]
  [18 19 20]
  [27 28 29]]]


3-D array sliced from first row to last:
 [[[ 4  5  6]
  [15 16 17]
  [24 25 26]]

 [[ 7  8  9]
  [18 19 20]
  [27 28 29]]]


In [52]:
# Negative slicing and indexing
import numpy as np
arr = np.array([10,20,30,40,50,60,70,80,90])
print("Element at index 2 or -7 of an array arr:",arr[-7])
print("Sliced Element from index -8 or 2 and -3 or 6 of an array arr:",arr[-8:-3])

Element at index 2 or -7 of an array arr: 30
Sliced Element from index -8 or 2 and -3 or 6 of an array arr: [20 30 40 50 60]


# In which method can we assign a single assignment or iterable? 
ANS. In indexing only
# In how many ways can we perform indexing in NumPy? 
ANS. 2 (Basic indexing and advance indexing)

In [67]:
a=np.arange(10)
print(a[1:8:2])

[1 3 5 7]


In [71]:
# We can also combine assignment and slicing
a=np.arange(10)
a[5:]=20
print(a)
b=np.arange(5)
a[5:]=b[::-1]
print(a)

[ 0  1  2  3  4 20 20 20 20 20]
[0 1 2 3 4 4 3 2 1 0]


# _COPIES AND VIEWS

In [75]:
a=np.arange(10)
print(a)
b=a[::2]
print(b)
c=a[::2].copy()
print(c)
print(np.shares_memory(a,b))
print(np.shares_memory(a,c))

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]
[0 2 4 6 8]
True
False


# _FANCY INDEXING_ : Numpy arrays can be indexed with slices but also with boolean or integer arrays(mask).This method is called fancy indexing.
It creates copies not views.

In [79]:
# Using Boolean mask
a=np.random.randint(0,20,15)
print(a)
mask=(a%2==0)      #  Here,a%2==0 is boolean condition
b=a[mask]
print(b)
a[mask]=-1
print(a)

[ 6  2  6  8  7 10  0  4  7  2 14 12 13 10 19]
[ 6  2  6  8 10  0  4  2 14 12 10]
[-1 -1 -1 -1  7 -1 -1 -1  7 -1 -1 -1 13 -1 19]


# _NUMPY ARRAY ITERATIONS Using for and while loops_
Nditer is a multidimensional iterator object in the NumPy package that can traverse an array efficiently.
We can modify the array value by using an optional parameter of the nditer object called Op flags (operand flags).
We have to perform multiple loops to iterate over a multidimensional array. To avoid using multiple loops, we use a NumPy function called nditer.

In [53]:
# Using for loops:
import numpy as np
arr = np.arange(12)
arr1=arr.reshape(3,4)
print("arr1:\n",arr1)
print("Traversed array:")
for i in arr1:
   for j in i:
    print(j, end=' ')
# Using nditer function:
"""for i in np.nditer(arr1):
   print(i, end=' ')"""

arr1:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Traversed array:
0 1 2 3 4 5 6 7 8 9 10 11 