In [28]:
import pandas as pd
pd.__version__

'2.1.3'

In [29]:
# Series,DataFramme and Index are the objects of pandas
import pandas as pd
C=pd.Series([2.1,3.2,4.3],index=["A","B","C"])  # For integer values return int64
print(C)
C.values

A    2.1
B    3.2
C    4.3
dtype: float64


array([2.1, 3.2, 4.3])

In [30]:
#  C.index
C.keys()

Index(['A', 'B', 'C'], dtype='object')

In [31]:
list(C.items())

[('A', 2.1), ('B', 3.2), ('C', 4.3)]

In [32]:
C.index.name = 'label'
C

label
A    2.1
B    3.2
C    4.3
dtype: float64

In [33]:
import pandas as pd
C=pd.Series(["HI","HELLO","HEY"],index=["A","B","C"])
print(C)

A       HI
B    HELLO
C      HEY
dtype: object


In [34]:
import pandas as pd
C=pd.Series([True,False,True],index=["A","B","C"])
print(C)

A     True
B    False
C     True
dtype: bool


In [35]:
dict_1 = {'California': 38332521,'Texas': 26448193,'New York': 19651127,'Florida': 19552860,'Illinois': 12882135}
population = pd.Series(dict_1)
population

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

In [36]:
population["Texas"]

26448193

In [37]:
# slicing by explicit index
population['California':'New York']

California    38332521
Texas         26448193
New York      19651127
dtype: int64

In [38]:
#  slicing by implicit index
population[0:3]

California    38332521
Texas         26448193
New York      19651127
dtype: int64

In [39]:
# fancy indexing
population[['California','New York']]

California    38332521
New York      19651127
dtype: int64

In [40]:
database=pd.DataFrame({"Population": population})
database

Population
California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135

In [41]:
population.values

array([38332521, 26448193, 19651127, 19552860, 12882135], dtype=int64)

In [42]:
database["Population"]         # Mostly used method
# database.Population

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
Name: Population, dtype: int64

In [43]:
# Adding new ccolumn in a dataframe
database["Area"]=[236,345,189,289,277]
database

Population  Area
California    38332521   236
Texas         26448193   345
New York      19651127   189
Florida       19552860   289
Illinois      12882135   277

In [67]:
database.replace(345,221,inplace=True)
database

Population  Area
California    38332521   236
Texas         26448193   221
New York      19651127   189
Florida       19552860   289
Illinois      12882135   277

In [44]:
# Extracting some slices of data
# database.iloc[:2,:2]
database.loc[["California","Texas"],["Population","Area"]]

Population  Area
California    38332521   236
Texas         26448193   345

In [45]:
# Transpose the DataFrame i.e. Swapping rows and columns
database.T

California     Texas  New York   Florida  Illinois
Population    38332521  26448193  19651127  19552860  12882135
Area               236       345       189       289       277

In [46]:
# Practice A Dataframe: 
""" a	b
0	0	0
1	1	2
2	2	4"""

new_data=pd.DataFrame({"a":[0,1,2],"b":[0,2,4]},index=(0,1,2))
new_data

a  b
0  0  0
1  1  2
2  2  4

In [47]:
import pandas as pd
d={"one":pd.Series([1,2,3],index=["A","B","D"]),
   "two":pd.Series([1,2,3,4],index=["A","B","C","D"])}
df=pd.DataFrame(d)
print(df)
df["one"]

   one  two
A  1.0    1
B  2.0    2
C  NaN    3
D  3.0    4


A    1.0
B    2.0
C    NaN
D    3.0
Name: one, dtype: float64

In [48]:
import pandas as pd
d={"one":pd.Series([1,2,3],index=["A","B","D"]),
   "two":pd.Series([1,2,3,4],index=["A","B","C","D"])}
df=pd.DataFrame(d)
df.loc["B"]

one    2.0
two    2.0
Name: B, dtype: float64

In [49]:
df.loc["A":"C"]

one  two
A  1.0    1
B  2.0    2
C  NaN    3

In [50]:
df.iloc[2]

one    NaN
two    3.0
Name: C, dtype: float64

In [51]:
df.iloc[1:3]

one  two
B  2.0    2
C  NaN    3

In [52]:
df[2:4]

one  two
C  NaN    3
D  3.0    4

In [53]:
print("Adding a cnew column by passing as Series")
df["three"]=pd.Series([10,20,30],index=["A","B","C"])
df

Adding a cnew column by passing as Series


one  two  three
A  1.0    1   10.0
B  2.0    2   20.0
C  NaN    3   30.0
D  3.0    4    NaN

In [54]:
print("Adding a new column using existing columnsin DataFrame")
df["four"]=df["one"]+df["three"]
df

Adding a new column using existing columnsin DataFrame


one  two  three  four
A  1.0    1   10.0  11.0
B  2.0    2   20.0  22.0
C  NaN    3   30.0   NaN
D  3.0    4    NaN   NaN

In [55]:
val={"one":4,"three":df.two.max(),"four":df.three.mean()}
df=df.fillna(val)
df

one  two  three  four
A  1.0    1   10.0  11.0
B  2.0    2   20.0  22.0
C  4.0    3   30.0  20.0
D  3.0    4    4.0  20.0

In [56]:
# Changing datatype:
import pandas as pd
C=pd.Series([True,False,True],index=["A","B","C"],dtype=str)
print(type(C[1]))                       # check type of series

<class 'str'>


C:\Users\hp\AppData\Local\Temp\ipykernel_13544\2309999933.py:4: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(type(C[1]))                       # check type of series


In [57]:
import pandas as pd
df=pd.DataFrame()
print(df)
df

Empty DataFrame
Columns: []
Index: []


Empty DataFrame
Columns: []
Index: []

In [58]:
pd.Series([1, np.nan, 2, None])

0    1.0
1    NaN
2    2.0
3    NaN
dtype: float64

In [59]:
data={"NAME":["Uma","Bhavya","Ritika","Sashwat","Asha","Sushma"],"MATH":[56,78,89,None,45,79],"CHEM":[78,90,94,90,67,69]}
df=pd.DataFrame(data,index=["r1","r2","r3","r4","r5","r6"])
print(df)

       NAME  MATH  CHEM
r1      Uma  56.0    78
r2   Bhavya  78.0    90
r3   Ritika  89.0    94
r4  Sashwat   NaN    90
r5     Asha  45.0    67
r6   Sushma  79.0    69


In [60]:
data=[["Rishabh",23],["Ashu",35],["Sushma",20]]
df=pd.DataFrame(data,columns=["Name","Age"])
df

Name  Age
0  Rishabh   23
1     Ashu   35
2   Sushma   20

In [61]:
data=[{"a":23,"b":35,"c":12},{"a":90,"b":34,"c":56}]
df=pd.DataFrame(data)
df

a   b   c
0  23  35  12
1  90  34  56

In [62]:
data=[{"a":23,"b":35},{"a":90,"b":34,"c":56}]
df1=pd.DataFrame(data,index=["First","Second"],columns=["a","b"])
df2=pd.DataFrame(data,index=["First","Second"],columns=["a","b1"])
print(df1)
df2

         a   b
First   23  35
Second  90  34


a  b1
First   23 NaN
Second  90 NaN

In [63]:
df=pd.DataFrame([[1,2],[3,4]],columns=["a","b"])
df2=pd.DataFrame([[5,6],[7,8]],columns=["a","b"])
df=df.append(df2)
df

AttributeError: 'DataFrame' object has no attribute 'append'

In [ ]:
r=df.head()
s=df.head(3)
print(r,"\n")
print(s)
display(s)            # display shows data in gradient table form

      NAME  MATH  CHEM
0      Uma    56    78
1   Bhavya    78    90
2   Ritika    89    94
3  Sashwat    78    90
4     Asha    45    67 

     NAME  MATH  CHEM
0     Uma    56    78
1  Bhavya    78    90
2  Ritika    89    94


NAME  MATH  CHEM
0     Uma    56    78
1  Bhavya    78    90
2  Ritika    89    94

In [ ]:
u=df.tail()
v=df.tail(2)
print(u,"\n")
print(v)

      NAME  MATH  CHEM
1   Bhavya    78    90
2   Ritika    89    94
3  Sashwat    78    90
4     Asha    45    67
5   Sushma    79    69 

     NAME  MATH  CHEM
4    Asha    45    67
5  Sushma    79    69


In [ ]:
print("Deleting first column using del function")
del df["one"]
df

Deleting first column using del function


two  three  four
A    1   10.0  11.0
B    2   20.0  22.0
C    3   30.0   NaN
D    4    NaN   NaN

In [ ]:
print("Deleting another column using pop function")
df.pop("two")
df

Deleting another column using pop function


three  four
A   10.0  11.0
B   20.0  22.0
C   30.0   NaN
D    NaN   NaN

In [ ]:
i=df.info(data)
print(i)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   NAME    6 non-null      object 
 1   MATH    5 non-null      float64
 2   CHEM    6 non-null      int64  
dtypes: float64(1), int64(1), object(1)
memory usage: 276.0+ bytes
None


In [ ]:
import numpy as np
val=np.array([3,np.nan,8,9])
val

array([ 3., nan,  8.,  9.])

In [ ]:
1+np.nan,1*np.nan,val.sum(),val.min(),val.max()

(nan, nan, nan, nan, nan)

In [ ]:
# Sum, Max and Min of all non null values
np.nansum(val),np.nanmax(val),np.nanmin(val)

(20.0, 9.0, 3.0)

In [ ]:
import pandas as pd
data2=pd.DataFrame({"Age":[45,34,31],"Salary":[3000,4000,2000]})
print(data2)
print(data2.shape)
print(data2.size)
print(data2.describe())

   Age  Salary
0   45    3000
1   34    4000
2   31    2000
(3, 2)
6
             Age  Salary
count   3.000000     3.0
mean   36.666667  3000.0
std     7.371115  1000.0
min    31.000000  2000.0
25%    32.500000  2500.0
50%    34.000000  3000.0
75%    39.500000  3500.0
max    45.000000  4000.0


In [ ]:
print(data2.columns)
print(data2.values)
print(data2.dtypes)

Index(['Age', 'Salary'], dtype='object')
[[  45 3000]
 [  34 4000]
 [  31 2000]]
Age       int64
Salary    int64
dtype: object


In [ ]:
data=pd.DataFrame({"NAME":["Uma","Bhavya","Ritika","Sashwat","Asha","Sushma"],"MATH":[56,78,89,None,45,79],"CHEM":[78,90,94,90,67,69]})
print(data.isnull())
print(data.isnull().sum())

    NAME   MATH   CHEM
0  False  False  False
1  False  False  False
2  False  False  False
3  False   True  False
4  False  False  False
5  False  False  False
NAME    0
MATH    1
CHEM    0
dtype: int64


In [ ]:
data.notnull()

NAME   MATH  CHEM
0  True   True  True
1  True   True  True
2  True   True  True
3  True  False  True
4  True   True  True
5  True   True  True

In [ ]:
print(data.drop("MATH",axis=1),"\n")    # 1 or 'columns
print(data.drop([0,1],axis=0),"\n")     # 0 or 'index'
print(data.drop(2,axis='index'))        # Remove row of 2nd index

      NAME  CHEM
0      Uma    78
1   Bhavya    90
2   Ritika    94
3  Sashwat    90
4     Asha    67
5   Sushma    69 

      NAME  MATH  CHEM
2   Ritika  89.0    94
3  Sashwat   NaN    90
4     Asha  45.0    67
5   Sushma  79.0    69 

      NAME  MATH  CHEM
0      Uma  56.0    78
1   Bhavya  78.0    90
3  Sashwat   NaN    90
4     Asha  45.0    67
5   Sushma  79.0    69


In [ ]:
print(data.to_csv())

,NAME,MATH,CHEM
0,Uma,56.0,78
1,Bhavya,78.0,90
2,Ritika,89.0,94
3,Sashwat,,90
4,Asha,45.0,67
5,Sushma,79.0,69



In [ ]:
import pandas as pd
df=pd.read_csv(r"C:\Users\hp\Desktop\Employees_data.csv")
df

Name  Age  Salary  Department               Post Gender
0    Nitesh   34   40000     Finance    General Manager      M
1    Tamana   23   50000       Sales          Executive      F
2       Uma   21   30000   Marketing  Assistant manager      F
3    Ritika   29   20000    Security     Deputy Manager      F
4   Shubham   37   70000  Purchasing           Engineer      M
5  Himanshi   27   60000          HR        Supervisior      F
6    Akshat   30   55000          IT     Senior Manager      M
7    Kartik   26   90000     Quality    Senior Engineer      M
8     Rahul   38   82000         PPC             Helper      M

In [ ]:
data2=pd.DataFrame({"Age":[45,34,31],"Salary":[3000,None,2000]})
data2.corr()     # Applicable for only numerical dataframe

Age  Salary
Age     1.0     1.0
Salary  1.0     1.0

In [ ]:
data2.dropna() 

Age  Salary
0   45  3000.0
2   31  2000.0

In [ ]:
data2=pd.DataFrame({"Age":[45,45,31],"Salary":[3000,3000,2000]})
data2.drop_duplicates()

Age  Salary
0   45    3000
2   31    2000

In [ ]:
data=pd.DataFrame({"NAME":["Uma","Bhavya","Ritika","Sashwat","Asha","Sushma"],"MATH":[56,78,89,None,45,79],"CHEM":[78,90,94,90,67,69]})
data.fillna(0)   # Replace NaN value by 0.0 in MATH column

NAME  MATH  CHEM
0      Uma  56.0    78
1   Bhavya  78.0    90
2   Ritika  89.0    94
3  Sashwat   0.0    90
4     Asha  45.0    67
5   Sushma  79.0    69

In [ ]:
# forward-fill
data.fillna(method='ffill')

C:\Users\hp\AppData\Local\Temp\ipykernel_20412\3316037056.py:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data.fillna(method='ffill')


NAME  MATH  CHEM
0      Uma  56.0    78
1   Bhavya  78.0    90
2   Ritika  89.0    94
3  Sashwat  89.0    90
4     Asha  45.0    67
5   Sushma  79.0    69

In [ ]:
# back-fill
data.fillna(method='bfill')

C:\Users\hp\AppData\Local\Temp\ipykernel_20412\692461307.py:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data.fillna(method='bfill')


NAME  MATH  CHEM
0      Uma  56.0    78
1   Bhavya  78.0    90
2   Ritika  89.0    94
3  Sashwat  45.0    90
4     Asha  45.0    67
5   Sushma  79.0    69

In [ ]:
# Multiindex Creation
df = pd.DataFrame(np.random.rand(4, 2),
                  index=[['a', 'a', 'b', 'b'], [1, 2, 3, 4]],
                  columns=['Data1', 'Data2'])
df

Data1     Data2
a 1  0.193885  0.266909
  2  0.831186  0.565449
b 3  0.834436  0.029643
  4  0.797806  0.181450

In [ ]:
import numpy as np
x=[1,2,3]
y=[4,5,6]
z=[7,8,9]
np.concatenate((x,y,z))      # np.concatenate([x,y,z])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
x = [[1, 2],
     [3, 4]]
np.concatenate([x, x], axis=1)    # axis=1  --> columnwise

array([[1, 2, 1, 2],
       [3, 4, 3, 4]])

In [ ]:
# GROUPING:
import pandas as pd
df = pd.DataFrame({'key': ['A', 'B', 'C', 'A', 'B', 'C'],
                   'data': range(6)}, columns=['key', 'data'])
df

key  data
0   A     0
1   B     1
2   C     2
3   A     3
4   B     4
5   C     5

In [ ]:
df.groupby("key").sum()  # ssum() is aggreation function

data
key      
A       3
B       5
C       7

In [ ]:
import seaborn as sns
planets = sns.load_dataset('planets')
planets

method  number  orbital_period   mass  distance  year
0     Radial Velocity       1      269.300000   7.10     77.40  2006
1     Radial Velocity       1      874.774000   2.21     56.95  2008
2     Radial Velocity       1      763.000000   2.60     19.84  2011
3     Radial Velocity       1      326.030000  19.40    110.62  2007
4     Radial Velocity       1      516.220000  10.50    119.47  2009
...               ...     ...             ...    ...       ...   ...
1030          Transit       1        3.941507    NaN    172.00  2006
1031          Transit       1        2.615864    NaN    148.00  2007
1032          Transit       1        3.191524    NaN    174.00  2007
1033          Transit       1        4.125083    NaN    293.00  2008
1034          Transit       1        4.187757    NaN    260.00  2008

[1035 rows x 6 columns]

In [ ]:
planets.groupby("method")["orbital_period"].median()

method
Astrometry                         631.180000
Eclipse Timing Variations         4343.500000
Imaging                          27500.000000
Microlensing                      3300.000000
Orbital Brightness Modulation        0.342887
Pulsar Timing                       66.541900
Pulsation Timing Variations       1170.000000
Radial Velocity                    360.200000
Transit                              5.714932
Transit Timing Variations           57.011000
Name: orbital_period, dtype: float64